version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: psr-quiz-app
    working_dir: /var/www/
    volumes:
      - ../src:/var/www
    networks:
      - app-network
  
  db:
    image: mysql:5.7
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      - ./.env
    restart: on-failure
    volumes:
      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - mysql-db-volume:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:1.20.2-alpine
    container_name: psr-quiz-nginx
    ports:
      - 8000:80
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - app-network

volumes:
  mysql-db-volume:

networks:
  app-network:
    driver: bridge